### ISSUE TITLE
Unable to save Google API info

### ISSUE THREAD

**Issue by Natkeeran** [mnylc/islandora_multi_importer#30] opened 2017-08-11 14:10 UTC
## Steps to Reproduce
* Do a fresh install of the googleAPI-WIP branch
* Go to http://localhost:8000/admin/islandora/tools/multi_importer
* Input the Google API Info
* Save

## The expected behavior.
* Should save the api access info

## The actual, incorrect behavior.
Blanks the screen.  Produces the following error:
```
Notice: Undefined index: islandora_multi_importer_googleClientToken in islandora_multi_importer_google_default_password() (line 77 of /var/www/drupal/sites/all/modules/islandora_multi_importer/includes/admin.form.inc).
```

**Comment by DiegoPino** [comment] 2017-08-11 14:18
Nat, can't reproduce. But will start with a fresh install since probably something got carried over during  development that is not allowing me to make this fail. Just to be sure:
The google API Credentials are defined by 3 steps:
1. Create the credentials , app-id, etc (json file) from google dev console
2. Insert App ID and Secret into the admin form
3. You should see a third form element and a link, press the link
4. You will get a confirmation page from google and a token
5. Put the token in the  third form element, and save
6. MUlti importer will in that very moment replace the normal keys for a re-fresh keys set. 
Could you share with me the content of the islandora multi importer variables?

**Comment by DiegoPino** [comment] 2017-08-11 14:22
Should be solved (now I see the why) via https://github.com/mnylc/islandora_multi_importer/commit/9a8520d2f00d1c4909ccafea6d767ee0d09b2ada. Feel free to test. 
I need to document clearly, with screenshots the google API steps. the config UI needs some love?

**Comment by DiegoPino** [comment] 2017-08-11 14:34
@Natkeeran tested with  https://github.com/mnylc/islandora_multi_importer/commit/9a8520d2f00d1c4909ccafea6d767ee0d09b2ada and i get no blank screen. Maybe something got stuck in cache after the update from 1 minute ago?
My steps: pulled latest changes, 
I blanked my fields, added secret again, went to token URL, copied from there, saved, went to multi importer and fetched a remote google spreadsheet, no problem.

Should i try something different?

![oauth2](https://user-images.githubusercontent.com/6946023/29217698-8e720918-7e80-11e7-9843-380319e901ab.jpeg)
![oauth2 b](https://user-images.githubusercontent.com/6946023/29217696-8e5d45fa-7e80-11e7-90db-159ae7d29a96.jpeg)

**Comment by DiegoPino** [comment] 2017-08-11 14:35
@Natkeeran did you make a ```composer update``` when you fetched this branch? there are some new dependencies (google API), maybe they are silently failing if not present? also, do you have errors in /var/log/apache2/error.log

**Comment by Natkeeran** [comment] 2017-08-11 14:38
@DiegoPino I did not make composer update.  Will try that now.

**Comment by DiegoPino** [comment] 2017-08-11 14:43
These are the variables that should have been set and are needed.
Note: 🙈  secret stuff is scrambled/obscured and fake, so no worries, i'm not giving away anything!

```Shell
vagrant@islandora:/var/www/drupal/sites$ drush vget islandora_multi_importer_googleClientID
islandora_multi_importer_googleClientID: '4090389731745-5kl8f2adtgv9c6qgokt51ixph9103lrl.apps.googleusercontent.com'

vagrant@islandora:/var/www/drupal/sites$ drush vget islandora_multi_importer_googleClientAuthCode
islandora_multi_importer_googleClientAuthCode: '4/l0a1bt1slTBhuT4RNlTOwnaIMibz8V3XX5aGQdfYK-s'

vagrant@islandora:/var/www/drupal/sites$ drush vget islandora_multi_importer_googleClientSecret
islandora_multi_importer_googleClientSecret: '1Gljf9mYooAIJ4rA7uZu8bwO'

vagrant@islandora:/var/www/drupal/sites$ drush vget islandora_multi_importer_googleClientToken
islandora_multi_importer_googleClientToken: array (
  'access_token' => 'ja45.FlukBDwllFb411AgbyrGeh8PedgFMSgsPo8IFi8k1IA1BtOeu4HrpcYf7kXC1T3K8CMy-SO10Ds8YuelTSAZQ6rv9cjP0S2jo5DIi_q83nxw3eZNu6xdO6GniDvFW',
  'token_type' => 'Bearer',
  'expires_in' => 3600,
  'refresh_token' => '4/AIceqIe95yAMAIn_VdfhCqaIXiZ12I5Tt-iZCqLgA-w',
  'created' => 1502461728,
)
````

**Comment by Natkeeran** [comment] 2017-08-11 14:53
@DiegoPino The screen is back.  I am not getting the islandora_multi_importer_googleClientAuthCode.  Probably because I missed Step # 3.  I tried to repeat the Steps 1 and 2, but the always getting a Error 404 for the AuthCode link.  For the API, which Application Type do we need to select?
![importer1](https://user-images.githubusercontent.com/1827166/29218605-4f6e96fc-7e83-11e7-8111-b7f4fd09edb7.png)

**Comment by DiegoPino** [comment] 2017-08-11 14:57
@Natkeeran "Other" is fine (don't go for Playstation4! 😬 ) Once you got your json file with secret, APP ID, etc , you need to also activate for that App-id Spreadsheet access: going to:
https://console.developers.google.com/apis/api/sheets.googleapis.com/overview?project=yourproject-id

**Comment by Natkeeran** [comment] 2017-08-11 14:58
Ok, finally, seems to have the correct authentication code with Other.  Will test the ingest workflow with google sheet.  Nice.  Thanks.

**Comment by DiegoPino** [comment] 2017-08-11 14:59
If you want, i can debug, and test step by step and document it. Probably i did not test what happens if i type wrongly, forget one step good enough?

**Comment by DiegoPino** [comment] 2017-08-11 14:59
@Natkeeran should i close this one as "fixed" and open a new one with "Diego, please document this!" ?

**Comment by Natkeeran** [comment] 2017-08-11 15:00
@DiegoPino I'll document the steps with screen shots to enable google api integration.  Better for a user to do this documentation : )

**Comment by DiegoPino** [comment] 2017-08-11 15:01
@Natkeeran jajaja. True. Not even i trust my docs 👍

**Closed** 2017-08-11 15:03 UTC
