### ISSUE TITLE
 MODS to DC XSLT not being triggered

### ISSUE THREAD

**Issue by astrohm** [mnylc/islandora_multi_importer#95] opened 2018-12-13 15:43 UTC
We're having some trouble with the MODS to DC transform. We've edited the default XSLT and updated the file located in the /islandora_xml_forms/builder/transforms directory and the IMI directory, and we've confirmed that if we use the Islandora UI to ingest and item, the transformation of the MODS is happening correctly and the resulting DC file looks the way it should. All content models are currently associated with the same default XSLT in the Form Builder settings. 

When using the IMI, we select the default XSLT file for the generation of the DC file, and the resulting DC file only contains a title (generated from the item label we select during the IMI import, I think) and the pid. None of the other metadata is included, even though our twig file is generating the correct MODS file. So somewhere the module is failing to trigger the transform. 

Thanks for taking a look!

**Comment by DiegoPino** [comment] 2018-12-13 15:49
@astrohm cool. Looking at it now. Thanks for reporting

**Comment by astrohm** [comment] 2018-12-17 21:41
We had loaded a new file into the module filesystem. We've got a slightly customized MODS to DC that we'd like to use, but aren't picky on whether we select it via the UI or just put it in a directory.

**Comment by McFateM** [comment] 2018-12-17 21:49
Same with me.  I have a custom xslt too, but it’s not critical.  Would be nice to have.

**Comment by DiegoPino** [comment] 2018-12-19 18:57
@astrohm @McFateM @patdunlavey. I feel #97 is ready to test. 

I added:
1. if `admin/islandora/xmlform/settings`Use Default DC XSLTs` is unset
1.2 Derive DC from MODS using the internal XSLT if DC was not already generated by some other means (like an uploaded file or a twig template) and MODs actually exist.
1.2 Try to derive. If it fails, log, if not ingest the damn thing.

Also: this pull also generates an empty Collection Policy 👀 on newly created Collections. Also, it includes a new RELS-EXT merging option when using this for updating. I feel it is still 95% accurate but getting there.

This is now working for Newly created objects. Not sure what would be the expected behavior for updates so open to suggestions (since in that case, DC will always exist!).

I decided for now (time constraints) not to add a form element in the admin page to set up the XSLT value. Mostly because it would require some dB logic probably or exposing filesystem (if no DB logic) to the ingester. I wanted to reuse the XML forms XLST management class but then i noticed there is not a "plain" get, only a "get if associated to CMODEL", which well, was not what I wanted.

I really hope this does not affect in any way performance (for those without default XSLT) since now more stuff happens on each ingested object. Finally, if you have  default XSLT, please make sure your CMODELS are actually mapped. I'm not defaulting to "derive it the IMI way" if someone forgot to map their manuscript CMODEL to an XSLT transformation!

**Comment by astrohm** [comment] 2018-12-21 14:55
We're still not seeing the Mods to DC file in the module directory being activated, but I'm beginning to think that there's some user error involved on our end. Perhaps if others aren't seeing this, we can chat via email or another means to see what we're potentially doing wrong.

**Comment by astrohm** [comment] 2019-01-15 21:10
We'd missed the last updates on the branch -- everything is working as expected now, thanks!

**Comment by DiegoPino** [comment] 2019-02-27 14:47
Fixed by 
https://github.com/mnylc/islandora_multi_importer/commit/d88084fae88a8e8dd4b71fec4f8dbef348c539a4 and merged to master

**Closed by DiegoPino** 2019-02-27 14:47 UTC
Labels: bug, enhancement
